import os

SANDBOX_PATH = "D:\\atlas_sandbox"
MEMORY_DB_PATH = "./atlas_memory"

WORKER_MODEL = "qwen2.5-coder:3b"
ARCHITECT_LOCAL_MODEL = "qwen2.5-coder:14b"
BUTLER_MODEL = "llama3.1:latest"
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")

WORKER_MAX_STEPS = 8
BASH_TIMEOUT = 15
OLLAMA_KEEP_ALIVE = -1

DMN_MIN_IDLE_SECONDS = 300
DMN_WANDER_INTERVAL_MIN = 300
DMN_WANDER_INTERVAL_MAX = 900

SESSION_SUMMARIZE_EVERY_N_TURNS = 20
SHORT_TERM_MEMORY_SIZE = 10

VOICE_BLEND = {'bm_george': 0.7, 'bm_fable': 0.3}